using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using RentalManager.Data;
namespace RentalManager.Services;
public sealed class ClientAccountService(IDbContextFactory<RentalDbContext> factory):IClientAccountService {
 public async Task<ClientSession?> VerifyAsync(string username,string password){await using var db=await factory.CreateDbContextAsync();var account=await db.ClientAccounts.AsNoTracking().SingleOrDefaultAsync(x=>x.Username==username.Trim()&&x.Enabled);if(account is null||new PasswordHasher<string>().VerifyHashedPassword(account.Username,account.PasswordHash,password)==PasswordVerificationResult.Failed)return null;Audit(db,account.Username,"ClientSignIn",account.Id);await db.SaveChangesAsync();return new(account.Id,account.TenantId,account.Username,account.SecurityStamp,account.MustChangePassword);}
 public async Task<bool> ValidateAsync(int id,int tenantId,string username,string? stamp,CancellationToken token=default){await using var db=await factory.CreateDbContextAsync(token);return await db.ClientAccounts.AsNoTracking().AnyAsync(x=>x.Id==id&&x.TenantId==tenantId&&x.Username==username&&x.Enabled&&x.SecurityStamp==stamp,token);}
 public async Task<bool> ChangePasswordAsync(int id,string current,string password){if(current==password)throw new InvalidOperationException("Choose a different password from your current password.");if(password.Length<12||password.Length>200)throw new InvalidOperationException("Password must be 12–200 characters.");await using var db=await factory.CreateDbContextAsync();var account=await db.ClientAccounts.SingleOrDefaultAsync(x=>x.Id==id&&x.Enabled);if(account is null)return false;var hasher=new PasswordHasher<string>();if(hasher.VerifyHashedPassword(account.Username,account.PasswordHash,current)==PasswordVerificationResult.Failed)return false;account.PasswordHash=hasher.HashPassword(account.Username,password);account.MustChangePassword=false;account.SecurityStamp=Guid.NewGuid().ToString("N");Audit(db,account.Username,"ClientPassword",id);await db.SaveChangesAsync();return true;}
 public async Task<IReadOnlyList<ClientAccountInfo>> ListAsync(){await using var db=await factory.CreateDbContextAsync();return await (from a in db.ClientAccounts.AsNoTracking() join t in db.Tenants on a.TenantId equals t.Id orderby t.FullName select new ClientAccountInfo(a.Id,t.Id,t.FullName,a.Username,a.Enabled,a.MustChangePassword)).ToListAsync();}
 public async Task CreateAsync(ClientProvision input,string actor){await using var db=await factory.CreateDbContextAsync();if(!await db.Tenants.AnyAsync(x=>x.Id==input.TenantId))throw new InvalidOperationException("Select an existing tenant.");if(await db.ClientAccounts.AnyAsync(x=>x.TenantId==input.TenantId||x.Username==input.Username))throw new InvalidOperationException("This tenant or username already has a client account.");var account=new ClientAccount{TenantId=input.TenantId,Username=input.Username,PasswordHash=new PasswordHasher<string>().HashPassword(input.Username,input.TemporaryPassword)};db.ClientAccounts.Add(account);await using var tx=await db.Database.BeginTransactionAsync();try{await db.SaveChangesAsync();Audit(db,actor,"CreateClient",account.Id);await db.SaveChangesAsync();await tx.CommitAsync();}catch(DbUpdateException e){throw new RentalPersistenceException("Unable to create the client account. Check duplicate usernames or tenant accounts.",e);}}
 public async Task ResetAsync(int id,string temporaryPassword,string actor){await using var db=await factory.CreateDbContextAsync();var account=await db.ClientAccounts.SingleOrDefaultAsync(x=>x.Id==id)??throw new InvalidOperationException("Client account not found.");account.PasswordHash=new PasswordHasher<string>().HashPassword(account.Username,temporaryPassword);account.MustChangePassword=true;account.SecurityStamp=Guid.NewGuid().ToString("N");Audit(db,actor,"ResetClient",id);await db.SaveChangesAsync();}
 public async Task EnableAsync(int id,bool enabled,string actor){await using var db=await factory.CreateDbContextAsync();var account=await db.ClientAccounts.SingleOrDefaultAsync(x=>x.Id==id)??throw new InvalidOperationException("Client account not found.");account.Enabled=enabled;account.SecurityStamp=Guid.NewGuid().ToString("N");Audit(db,actor,enabled?"EnableClient":"DisableClient",id);await db.SaveChangesAsync();}
 static void Audit(RentalDbContext db,string actor,string action,int id)=>db.Audit.Add(new(){Actor=actor,Action=action,Entity="ClientAccount",EntityId=id,At=DateTimeOffset.UtcNow});
}
