using Microsoft.EntityFrameworkCore;
using RentalManager.Data;
namespace RentalManager.Services;
public sealed class EfClientPortalRepository(IDbContextFactory<RentalDbContext> factory):IClientPortalRepository {
 public async Task<ClientDashboard> LoadAsync(int tenantId){await using var db=await factory.CreateDbContextAsync();var name=await db.Tenants.Where(x=>x.Id==tenantId).Select(x=>x.FullName).SingleAsync();var leases=await db.Leases.AsNoTracking().Where(x=>x.TenantId==tenantId).Join(db.Properties,x=>x.PropertyId,x=>x.Id,(l,p)=>new ClientLease(l.Id,p.Name,l.StartDate,l.EndDate,l.MonthlyRent,l.Status,l.NoticeDays,l.RenewalIntervalMonths)).OrderByDescending(x=>x.Start).ToListAsync();var contracts=await db.Contracts.AsNoTracking().Join(db.Leases.Where(x=>x.TenantId==tenantId),x=>x.LeaseId,x=>x.Id,(c,l)=>new ClientContract(c.Id,l.Id,c.CreatedAt)).OrderByDescending(x=>x.CreatedAt).ToListAsync();var currency=await db.Landlords.Select(x=>x.Currency).FirstOrDefaultAsync()??"TZS";return new(name,currency,leases,contracts,await RequestQuery(db).Where(x=>x.TenantId==tenantId).Select(x=>x.Info).ToListAsync());}
 public async Task<string?> ContractAsync(int id,int tenantId){await using var db=await factory.CreateDbContextAsync();return await db.Contracts.AsNoTracking().Where(x=>x.Id==id).Join(db.Leases.Where(x=>x.TenantId==tenantId),x=>x.LeaseId,x=>x.Id,(c,l)=>c.Html).SingleOrDefaultAsync();}
 public async Task SubmitAsync(RenewalDraft draft,int tenantId,string actor,DateOnly today){await using var db=await factory.CreateDbContextAsync();await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var lease=await db.Leases.SingleOrDefaultAsync(x=>x.Id==draft.LeaseId&&x.TenantId==tenantId&&x.Status=="Active")??throw new InvalidOperationException("Select your active lease.");if(lease.EndDate<today.AddDays(-30))throw new InvalidOperationException("Contact the landlord about this expired lease.");var intent=await db.RenewalIntents.SingleOrDefaultAsync(x=>x.LeaseId==lease.Id);if(intent is null){intent=new(){LeaseId=lease.Id,TenantId=tenantId};db.RenewalIntents.Add(intent);}intent.ContinueRent=draft.ContinueRent;intent.Months=draft.ContinueRent?draft.Months:0;intent.Message=draft.Message.Trim();intent.SubmittedAt=DateTimeOffset.UtcNow;intent.Reviewed=false;intent.Response="";await db.SaveChangesAsync();db.Audit.Add(new(){Actor=actor,Action="RenewalIntent",Entity="Lease",EntityId=lease.Id,At=DateTimeOffset.UtcNow});db.Notifications.Add(new(){Title="Client rental decision",Message=$"A client submitted {(draft.ContinueRent?"a request to continue":"a plan to leave")} for lease #{lease.Id}.",Link="/clients?tab=renewals",CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task<IReadOnlyList<RenewalInfo>> RequestsAsync(){await using var db=await factory.CreateDbContextAsync();return await RequestQuery(db).OrderBy(x=>x.Info.Reviewed).ThenByDescending(x=>x.Info.SubmittedAt).Select(x=>x.Info).ToListAsync();}
 public async Task ReviewAsync(int id,string response,string actor){await using var db=await factory.CreateDbContextAsync();var intent=await db.RenewalIntents.SingleOrDefaultAsync(x=>x.Id==id)??throw new InvalidOperationException("Request not found.");intent.Reviewed=true;intent.Response=response;db.Audit.Add(new(){Actor=actor,Action="ReviewRenewal",Entity="Lease",EntityId=intent.LeaseId,At=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
 record RequestRow(int TenantId,RenewalInfo Info);
 static IQueryable<RequestRow> RequestQuery(RentalDbContext db)=>from r in db.RenewalIntents.AsNoTracking() join l in db.Leases on r.LeaseId equals l.Id join t in db.Tenants on r.TenantId equals t.Id join p in db.Properties on l.PropertyId equals p.Id select new RequestRow(r.TenantId,new RenewalInfo(r.Id,r.LeaseId,t.FullName,p.Name,r.ContinueRent,r.Months,r.Message,r.SubmittedAt,r.Reviewed,r.Response));
}
