using Microsoft.EntityFrameworkCore;
using RentalManager.Data;
namespace RentalManager.Services;
public sealed class EfClientPortalRepository(IDbContextFactory<RentalDbContext> factory):IClientPortalRepository {
 public async Task<ClientDashboard> LoadAsync(int tenantId){
  await using var db=await factory.CreateDbContextAsync();
  var name=await db.Tenants.Where(x=>x.Id==tenantId).Select(x=>x.FullName).SingleAsync();
  var leases=await (from l in db.Leases.AsNoTracking() join p in db.Properties on l.PropertyId equals p.Id where l.TenantId==tenantId orderby l.StartDate descending select new ClientLease(l.Id,p.Name,l.StartDate,l.EndDate,l.MonthlyRent,l.Status,l.NoticeDays,l.RenewalIntervalMonths)).ToListAsync();
  var contracts=await (from c in db.Contracts.AsNoTracking() join l in db.Leases on c.LeaseId equals l.Id where l.TenantId==tenantId orderby c.CreatedAt descending select new ClientContract(c.Id,l.Id,c.CreatedAt)).ToListAsync();
  var currency=await db.Landlords.Select(x=>x.Currency).FirstOrDefaultAsync()??"TZS";
  var requests=await RequestQuery(db).Where(x=>x.Request.TenantId==tenantId).Select(x=>new RenewalInfo(x.Request.Id,x.Request.LeaseId,x.TenantName,x.PropertyName,x.Request.ContinueRent,x.Request.Months,x.Request.Message,x.Request.SubmittedAt,x.Request.Reviewed,x.Request.Response)).ToListAsync();
  return new(name,currency,leases,contracts,requests);
 }
 public async Task<string?> ContractAsync(int id,int tenantId){await using var db=await factory.CreateDbContextAsync();return await db.Contracts.AsNoTracking().Where(x=>x.Id==id).Join(db.Leases.Where(x=>x.TenantId==tenantId),x=>x.LeaseId,x=>x.Id,(c,l)=>c.Html).SingleOrDefaultAsync();}
 public async Task SubmitAsync(RenewalDraft draft,int tenantId,string actor,DateOnly today){await using var db=await factory.CreateDbContextAsync();await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var lease=await db.Leases.SingleOrDefaultAsync(x=>x.Id==draft.LeaseId&&x.TenantId==tenantId&&x.Status=="Active")??throw new InvalidOperationException("Select your active lease.");if(lease.EndDate<today.AddDays(-30))throw new InvalidOperationException("Contact the landlord about this expired lease.");var intent=await db.RenewalIntents.SingleOrDefaultAsync(x=>x.LeaseId==lease.Id);if(intent is null){intent=new(){LeaseId=lease.Id,TenantId=tenantId};db.RenewalIntents.Add(intent);}intent.ContinueRent=draft.ContinueRent;intent.Months=draft.ContinueRent?draft.Months:0;intent.Message=draft.Message.Trim();intent.SubmittedAt=DateTimeOffset.UtcNow;intent.Reviewed=false;intent.Response="";await db.SaveChangesAsync();db.Audit.Add(new(){Actor=actor,Action="RenewalIntent",Entity="Lease",EntityId=lease.Id,At=DateTimeOffset.UtcNow});db.Notifications.Add(new(){Title="Client rental decision",Message=$"A client submitted {(draft.ContinueRent?"a request to continue":"a plan to leave")} for lease #{lease.Id}.",Link="/clients?tab=renewals",CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task<IReadOnlyList<RenewalInfo>> RequestsAsync(){await using var db=await factory.CreateDbContextAsync();return await RequestQuery(db).OrderBy(x=>x.Request.Reviewed).ThenByDescending(x=>x.Request.SubmittedAt).Select(x=>new RenewalInfo(x.Request.Id,x.Request.LeaseId,x.TenantName,x.PropertyName,x.Request.ContinueRent,x.Request.Months,x.Request.Message,x.Request.SubmittedAt,x.Request.Reviewed,x.Request.Response)).ToListAsync();}
 public async Task ReviewAsync(int id,string response,string actor){await using var db=await factory.CreateDbContextAsync();var intent=await db.RenewalIntents.SingleOrDefaultAsync(x=>x.Id==id)??throw new InvalidOperationException("Request not found.");intent.Reviewed=true;intent.Response=response;db.Audit.Add(new(){Actor=actor,Action="ReviewRenewal",Entity="Lease",EntityId=intent.LeaseId,At=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
 sealed class RequestRow {public RenewalIntent Request{get;set;}=null!;public string TenantName{get;set;}="";public string PropertyName{get;set;}="";}
 static IQueryable<RequestRow> RequestQuery(RentalDbContext db)=>from r in db.RenewalIntents.AsNoTracking() join l in db.Leases on r.LeaseId equals l.Id join t in db.Tenants on r.TenantId equals t.Id join p in db.Properties on l.PropertyId equals p.Id select new RequestRow{Request=r,TenantName=t.FullName,PropertyName=p.Name};
}
