using Microsoft.EntityFrameworkCore;
using RentalManager.Data;
namespace RentalManager.Services;
public sealed class EfWorkspaceRepository(IDbContextFactory<RentalDbContext> factory):IWorkspaceRepository {
 public async Task<WorkspaceSummary> SummaryAsync(string actor){await using var db=await factory.CreateDbContextAsync();var profile=await db.Admins.AsNoTracking().Where(x=>x.Id==1&&x.Username==actor).Select(x=>new UserProfile(x.Username,x.DisplayName,x.Email,x.Phone)).SingleOrDefaultAsync()??throw new UnauthorizedAccessException("Sign in again to load your profile.");return new(profile,await db.Notifications.CountAsync(x=>!x.IsRead));}
 public async Task SaveProfileAsync(ProfileEdit profile,string actor){await using var db=await factory.CreateDbContextAsync();var admin=await db.Admins.SingleOrDefaultAsync(x=>x.Id==1&&x.Username==actor)??throw new UnauthorizedAccessException();admin.DisplayName=profile.DisplayName;admin.Email=profile.Email;admin.Phone=profile.Phone;Audit(db,actor,"UpdateProfile","Admin",1);db.Notifications.Add(new(){Title="Profile updated",Message="Your profile information was updated.",Link="/profile",CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();}
 public async Task<CommentPage> CommentsAsync(CommentFilter filter,string actor){filter.Validate();await using var db=await factory.CreateDbContextAsync();var query=db.Comments.AsNoTracking().AsQueryable();if(filter.Status!="all")query=query.Where(x=>x.Resolved==(filter.Status=="resolved"));if(!string.IsNullOrWhiteSpace(filter.Search)){var search=filter.Search.Trim();query=query.Where(x=>x.Subject.Contains(search)||x.Message.Contains(search)||x.Author.Contains(search));}return new(await query.OrderByDescending(x=>x.CreatedAt).ThenByDescending(x=>x.Id).Skip((filter.Page-1)*25).Take(25).ToListAsync(),await query.CountAsync(),filter.Page);}
 public async Task AddCommentAsync(CommentDraft draft,string actor){await using var db=await factory.CreateDbContextAsync();await using var tx=await db.Database.BeginTransactionAsync();var comment=new RentalComment{Subject=draft.Subject,Message=draft.Message,Author=actor,CreatedAt=DateTimeOffset.UtcNow};db.Comments.Add(comment);await db.SaveChangesAsync();Audit(db,actor,"CreateComment","Comment",comment.Id);db.Notifications.Add(new(){Title="New comment",Message=$"{actor} added a comment: {draft.Subject}",Link="/comments",CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task ResolveCommentAsync(int id,bool resolved,string actor){await using var db=await factory.CreateDbContextAsync();var comment=await db.Comments.SingleOrDefaultAsync(x=>x.Id==id)??throw new InvalidOperationException("Comment no longer exists.");if(comment.Resolved==resolved)return;comment.Resolved=resolved;Audit(db,actor,resolved?"ResolveComment":"ReopenComment","Comment",id);await db.SaveChangesAsync();}
 public async Task<NotificationPage> NotificationsAsync(bool unreadOnly,int page,string actor){await using var db=await factory.CreateDbContextAsync();var query=db.Notifications.AsNoTracking().AsQueryable();if(unreadOnly)query=query.Where(x=>!x.IsRead);return new(await query.OrderByDescending(x=>x.CreatedAt).ThenByDescending(x=>x.Id).Skip((page-1)*25).Take(25).ToListAsync(),await query.CountAsync(),await db.Notifications.CountAsync(x=>!x.IsRead),page);}
 public async Task MarkReadAsync(int? id,string actor){await using var db=await factory.CreateDbContextAsync();var query=db.Notifications.Where(x=>!x.IsRead);if(id.HasValue)query=query.Where(x=>x.Id==id.Value);await query.ExecuteUpdateAsync(s=>s.SetProperty(x=>x.IsRead,true));}
 static void Audit(RentalDbContext db,string actor,string action,string entity,int id)=>db.Audit.Add(new(){Actor=actor,Action=action,Entity=entity,EntityId=id,At=DateTimeOffset.UtcNow});
}
