<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><RootNamespace>RentalManager</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../RentalManager.Domain/RentalManager.Domain.csproj" /><ProjectReference Include="../RentalManager.Application/RentalManager.Application.csproj" /></ItemGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>